/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.22
 * Generated at: 2015-10-25 09:08:00 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index3_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/Users/Hanlu/Desktop/qinyang_oa_system/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/system/WEB-INF/lib/jstl-impl-1.2.jar!/META-INF/c-1_0-rt.tld", Long.valueOf(1308098170000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-impl-1.2.jar", Long.valueOf(1444880074000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head lang=\"en\">\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <title></title>\n");
      out.write("    <link rel=\"stylesheet\" href=\"http://101.200.196.121:8080/oa/css/all.css\"/>\n");
      out.write("</head>\"/>\n");
      out.write("</head>\n");
      out.write("<body style=\"background-color: #e5e5e5\">\n");
      out.write("<div class=\"header\">\n");
      out.write("    <!--头部header区域-->\n");
      out.write("    <div class=\"h_content\">\n");
      out.write("        <!--左侧Logo及文字-->\n");
      out.write("        <div class=\"logo\">\n");
      out.write("            <i></i>\n");
      out.write("            <span></span>\n");
      out.write("        </div>\n");
      out.write("        <!--右侧导航部分-->\n");
      out.write("        <div class=\"menu\">\n");
      out.write("            <ul>\n");
      out.write("                <li><a href=\"../index.html\"><i class=\"icon\"></i><span>退出</span></a></li>\n");
      out.write("                <li><a href=\"../sz/sz.html\"><i class=\"icon_s icon\"></i>设置</a></li>\n");
      out.write("                <li><a href=\"../xx/xx.html\"><i class=\"icon_m icon\"></i>消息</a></li>\n");
      out.write("                <li><a href=\"../kh/kh.html\"><i class=\"icon_k icon\"></i>考核</a></li>\n");
      out.write("                <li><a href=\"../tz/tz.html\"><i class=\"icon_t icon\"></i>台账</a></li>\n");
      out.write("                <li><a href=\"../gz/gz.html\"><i class=\"icon_g icon\"></i>工作</a></li>\n");
      out.write("                <li><a href=\"../wfw/fza.html\"><i></i>五服务</a></li>\n");
      out.write("                <li><a href=\"../sl/sl.html\"><i class=\"icon_l icon\"></i>四联</a></li>\n");
      out.write("            </ul>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</div>\n");
      out.write("<!--主体-->\n");
      out.write("<div class=\"m_content\">\n");
      out.write("    <div class=\"loginindex\">\n");
      out.write("        <div class=\"mokuaione\">\n");
      out.write("            <div class=\"mokuai\">\n");
      out.write("                <a class=\"mokuaitu\">\n");
      out.write("                    <img src=\"http://101.200.196.121:8080/oa/css/images/slt_03.jpg\" alt=\"\"/>\n");
      out.write("                    <i style=\"display: none\"></i>\n");
      out.write("                    <span style=\"display: none\">· 市委常委联系乡镇（办事处）党（工）委<br/>\n");
      out.write("· 乡镇（办事处）党员领导干部联系村级党组织<br/>\n");
      out.write("· 村（社区）党员干部联系党员<br/>\n");
      out.write("· 党员联系群众</span>\n");
      out.write("                </a>\n");
      out.write("                <a class=\"mokuaizi\" >四联</a>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"mokuai\">\n");
      out.write("                <a class=\"mokuaitu\">\n");
      out.write("                    <img src=\"http://101.200.196.121:8080/oa/css/images/wfwt_05.jpg\" alt=\"\"/>\n");
      out.write("                    <i style=\"display: none\"></i>\n");
      out.write("                    <span style=\"display: none\">· 市委常委联系乡镇（办事处）党（工）委<br/>\n");
      out.write("· 乡镇（办事处）党员领导干部联系村级党组织<br/>\n");
      out.write("· 村（社区）党员干部联系党员<br/>\n");
      out.write("· 党员联系群众</span>\n");
      out.write("                </a>\n");
      out.write("                <h4 class=\"mokuaizi\" >五服务</h4>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"mokuai marginr\">\n");
      out.write("                <a class=\"mokuaitu\">\n");
      out.write("                    <img src=\"http://101.200.196.121:8080/oa/css/images/gzt_07.jpg\" alt=\"\"/>\n");
      out.write("                    <i style=\"display: none\"></i>\n");
      out.write("                    <span style=\"display: none\">· 市委常委联系乡镇（办事处）党（工）委<br/>\n");
      out.write("· 乡镇（办事处）党员领导干部联系村级党组织<br/>\n");
      out.write("· 村（社区）党员干部联系党员<br/>\n");
      out.write("· 党员联系群众</span>\n");
      out.write("                </a>\n");
      out.write("                <h4 class=\"mokuaizi\" >工作</h4>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"mokuaione\">\n");
      out.write("            <div class=\"mokuai\">\n");
      out.write("                <a class=\"mokuaitu\">\n");
      out.write("                    <img src=\"http://101.200.196.121:8080/oa/css/images/glb_12.jpg\" alt=\"\"/>\n");
      out.write("                    <i style=\"display: none\"></i>\n");
      out.write("                    <span style=\"display: none\">· 市委常委联系乡镇（办事处）党（工）委<br/>\n");
      out.write("· 乡镇（办事处）党员领导干部联系村级党组织<br/>\n");
      out.write("· 村（社区）党员干部联系党员<br/>\n");
      out.write("· 党员联系群众</span>\n");
      out.write("                </a>\n");
      out.write("                <h4 class=\"mokuaizi\" >管理</h4>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"mokuai\">\n");
      out.write("                <a class=\"mokuaitu\">\n");
      out.write("                    <img src=\"http://101.200.196.121:8080/oa/css/images/khb_13.jpg\" alt=\"\"/>\n");
      out.write("                    <i style=\"display: none\"></i>\n");
      out.write("                    <span style=\"display: none\">· 市委常委联系乡镇（办事处）党（工）委<br/>\n");
      out.write("· 乡镇（办事处）党员领导干部联系村级党组织<br/>\n");
      out.write("· 村（社区）党员干部联系党员<br/>\n");
      out.write("· 党员联系群众</span>\n");
      out.write("                </a>\n");
      out.write("                <h4 class=\"mokuaizi\" >考核</h4>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"mokuai marginr\">\n");
      out.write("                <a class=\"mokuaitu\">\n");
      out.write("                    <img src=\"http://101.200.196.121:8080/oa/css/images/tzt_12.jpg\" alt=\"\"/>\n");
      out.write("                <i style=\"display: none\"></i>\n");
      out.write("                    <span style=\"display: none\">· 市委常委联系乡镇（办事处）党（工）委<br/>\n");
      out.write("· 乡镇（办事处）党员领导干部联系村级党组织<br/>\n");
      out.write("· 村（社区）党员干部联系党员<br/>\n");
      out.write("· 党员联系群众</span>\n");
      out.write("                </a>\n");
      out.write("                <h4 class=\"mokuaizi\" >台帐</h4>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("</div>\n");
      out.write("<script src=\"http://101.200.196.121:8080/oa/js/jquery-1.11.3.min.js\"></script>\n");
      out.write("<script src=\"http://101.200.196.121:8080/oa/js/My97DatePicker/WdatePicker.js\"></script>\n");
      out.write("<script src=\"http://101.200.196.121:8080/oa/js/style.js\"></script>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
