/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.22
 * Generated at: 2015-10-15 14:27:50 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write("\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<script type=\"text/javascript\" src=\"http://www.francescomalagrino.com/BootstrapPageGenerator/3/js/jquery-2.0.0.min.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"http://www.francescomalagrino.com/BootstrapPageGenerator/3/js/jquery-ui\"></script>\n");
      out.write("<link href=\"http://www.francescomalagrino.com/BootstrapPageGenerator/3/css/bootstrap-combined.min.css\" rel=\"stylesheet\" media=\"screen\">\n");
      out.write("<script type=\"text/javascript\" src=\"http://www.francescomalagrino.com/BootstrapPageGenerator/3/js/bootstrap.min.js\"></script>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("<div class=\"container-fluid\">\n");
      out.write("\t<div class=\"row-fluid\">\n");
      out.write("\t\t<div class=\"span12\">\n");
      out.write("\t\t\t<div class=\"tabbable\" id=\"tabs-105576\">\n");
      out.write("\t\t\t\t<ul class=\"nav nav-tabs\">\n");
      out.write("\t\t\t\t\t<li class=\"active\">\n");
      out.write("\t\t\t\t\t\t<a href=\"#panel-login\" data-toggle=\"tab\">个人</a>\n");
      out.write("\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t\t<li>\n");
      out.write("\t\t\t\t\t\t<a href=\"#panel-register\" data-toggle=\"tab\">后台</a>\n");
      out.write("\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t\t<li>\n");
      out.write("\t\t\t\t\t\t<a href=\"#panel-mail\" data-toggle=\"tab\">邮件</a>\n");
      out.write("\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t\t<li>\n");
      out.write("\t\t\t\t\t    <a href=\"#panel-task\" data-toggle=\"tab\">任务</a>\n");
      out.write("\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t</ul>\n");
      out.write("\t\t\t\t<div class=\"tab-content\">\n");
      out.write("\t\t\t\t\t<div class=\"tab-pane active\" id=\"panel-login\">\n");
      out.write("\t\t\t\t\t\t<table border=\"0\">\n");
      out.write("\t\t\t\t\t\t\t<form action=\"login.do\" method=\"post\">\n");
      out.write("\t\t\t                  <tr><td width=\"20%\">用户名</td><td><input type=\"text\" name=\"username\" /></td></tr>\n");
      out.write("                              <tr><td width=\"20%\">密  码</td><td><input type=\"password\" name=\"password\" /></td></tr>\n");
      out.write("                              <tr><td colspan=\"2\" align=\"center\"><input type=\"submit\" value=\"登陆\" />&nbsp;&nbsp;<input type=\"reset\" value=\"重置\"></td></tr>\n");
      out.write("\t\t\t                </form>\n");
      out.write("\t\t\t\t\t\t</table>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div class=\"tab-pane \" id=\"panel-register\">\n");
      out.write("\t\t\t\t\t\t<table border=\"0\">\n");
      out.write("\t\t\t\t\t\t\t<form action=\"register.do\" method=\"post\">\n");
      out.write("\t\t\t                  <tr><td width=\"20%\">用户名</td><td><input type=\"text\" name=\"username\" /></td></tr>\n");
      out.write("                              <tr><td width=\"20%\">密  码</td><td><input type=\"password\" name=\"password\" /></td></tr>\n");
      out.write("                              <tr><td colspan=\"2\" align=\"center\"><input type=\"submit\" value=\"添加用户\" />&nbsp;&nbsp;<input type=\"reset\" value=\"重置\"></td></tr>\n");
      out.write("\t\t\t                </form>\n");
      out.write("\t\t\t\t\t\t</table>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div class=\"tab-pane\" id=\"panel-mail\">\n");
      out.write("\t\t\t\t\t    <h2><a href=\"mail.jsp\">发邮件</a></h2>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div class=\"tab-pane\" id=\"panel-task\">\n");
      out.write("\t\t\t\t \t    <h2><a href=\"task.jsp\">发任务</a></h2>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("</div>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
